### ISSUE TITLE
Missing default settings

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-rust-analyzer#2]
The default settings need to be present in `"settings"` in LSP-rust-analyzer.sublime-settings, otherwise we send an empty dict

```
:: <-- rust-analyzer workspace/configuration(2): {'items': [{'section': 'rust-analyzer'}]}
:: >>> rust-analyzer 2: [{'assist': {'importEnforceGranularity': False}}]
```

**Comment by rchl** [comment]
Not necessarily a problem from the server perspective if it assumes defaults for everything but from the user perspective it's better if the default settings are included so that it's easy to see what's available. Of course people can and should use `LSP-json` but that's a bit more cumbersome if you just want to check out all the settings.

**Comment by Daggy1234** [comment]
Okay I'll add the default settings!

**Comment by Daggy1234** [comment]
9f02ab3f1e76cf248f36d7b7aa6bc4ff0eb2d60e Added Default config in commit.

**Comment by rchl** [comment]
Can you remove those?
https://github.com/sublimelsp/LSP-rust-analyzer/blob/86da3c686dc48909c212655ddcc2ab4b101e3174/LSP-rust-analyzer.sublime-settings#L155-L158

Those are not in the schema (on purpose) so those will trigger errors if using LSP-json

**Comment by Daggy1234** [comment]
Oh alrighty

**Comment by Daggy1234** [comment]
Closing this then!
