### ISSUE TITLE
Is it possible to cache the index results?

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-rust-analyzer#22]
It looks like rust-analyzer always starts to re-index the entire project anytime I start it. This can take quite a while. Is there a way to cache this index on disk so that it doesn't do that?

**Comment by rwols** [comment]
Might need an issue in the rust-analyzer repo. Though I'm no rust expert.

**Comment by rchl** [comment]
I'll just note that VSCode extension also doesn't seem to be doing any caching. Restarting VSCode reindexes the project.

**Comment by Rapptz** [comment]
This is unfortunately by design. The indexing is done by `cargo metadata` and there is a local level of caching from cargo's end, typically with the dependencies so the next time it is faster. However rust-analyzer still needs to build its own data in memory so it knows the project structure and data. Any improvement there would need to be within the server.

**Comment by rwols** [comment]
Already here I guess https://github.com/rust-analyzer/rust-analyzer/issues/4712

**Comment by rchl** [comment]
Not something we would can handle on the package side anyway.
