### ISSUE TITLE
Add stop server option

### ISSUE THREAD

**Issue by kshitjj** [sublimelsp/LSP-rust-analyzer#95]
Having the option to stop the rust analyzer server would be really good, as the rust analyzer takes a lot of CPU.

**Comment by kshitjj** [comment]
Well how I envision it is, there's an option to start and stop the server whenever I want. But why would one need the option to stop and start the server?

Rust-analyzer is RAM and CPU heavy, and when I am working on an rust project, I have might need to test/build/etc the project. So, running these "tasks" while the rust analyzer is running the background causes my PC to crash everytime.

So, having an option to stop the server while I am running some other task will be quite helpful.

**Comment by rchl** [comment]
You have

> There is already an option to disable server per-project (LSP: Disable Language Server in Project)

Why is that not sufficient.

If you want a different way of stopping and starting then you have to think of how that flow should work, especially from the UI standpoint. Also given good enough reasons for having another way to do what seems to be the same thing.

**Comment by predragnikolic** [comment]
Hello @kshitjj 

You have a couple of commands from the command pallete to start stop a server:
* `LSP: Disable Language Server Globally` (or  `LSP: Enable Language Server Globally`)
* `LSP: Disable Language Server in Project` (or `LSP: Enable Language Server in Project`)
* or  `Package Control: Disable package` (or  `Package Control: Enable package`)

I do not believe that we need more ways to stop a server than I listed above.
Thus I will close this issue.

If you still think otherwise, feel free to reopen it.
